mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: gvb_db
  user: root
  password: root
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: dev
upload:
  size: 2
  path: uploads/file
site_info:
  created_at: ""
  bei_an: ""
  title: ""
  qq_image: ""
  version: ""
  email: ""
  wechat_image: ""
  name: ""
  job: ""
  addr: ""
  slogan: ""
  slogan_en: ""
  web: ""
  bilibili_url: ""
  gitee_url: ""
  github_url: ""
qq:
  app_id: ""
  key: "111213"
  redirect: ""
qiniu:
  enable: true
  access_key: 
  secret_key: 
  bucket: 
  cdn: 
  zone: z2
  prefix: "gvb"
  size: 5
email:
  host: "111"
  port: 0
  user: ""
  password: abc
  default_from_email: ""
  use_ssl: false
  user_tls: false
jwt:
  secret: "1"
  expires: 1
  issuer: "1"
redis:
  ip: 127.0.0.1
  port: 6379
  password: ""
  pool_size: 100
es:
  host: "http://192.168.110.140"
  port: 9200
  user:
  password:
